meta:
  run_tag: prod_like
  timezone: UTC

data:
  # Long-format CSVs: date,asset,close (daily)
  barometer_prices: data/kraken/kraken_daily.csv   # can reuse the same CSV
  universe_prices:  data/kraken/kraken_eur_universe.csv
  prices_wide:      data/prices_eur.csv       # wide panel used by the backtester (date,asset,close)
  benchmarks: [XBTEUR, ETHEUR]

  # Map coin_id -> asset in your CSV
  # (adjust if your asset codes differ)
  symbol_map:
    bitcoin:  XBTEUR
    ethereum: ETHEUR
    solana:   SOLEUR

model_a:
  barometer_kind: btc_eth_sol_333
  lookbacks: [120, 180, 300]
  skip_days: 7
  enter_up_z:   0.25
  exit_up_z:    0.10
  enter_down_z: -0.25
  exit_down_z:  -0.10
  dwell_days: 5

model_b:
  barometer_kind: btc_eth_sol_333
  er_window: 20
  enter_strong: 0.30
  exit_strong:  0.25
  enter_weak:   0.20
  exit_weak:    0.25
  dwell_days: 3

model_c:
  rebalance: 4W-SUN
  N: 15
  cap: 0.25
  floor_eur: 250
  portfolio_eur: 10000
  skip_days: 3

allocator:
  exp_uptrend:   1.0
  exp_range:     1.0
  exp_downtrend: 0.0

backtest:
  start: "2024-09-19"
  end:   "2025-09-19"
  signal_lag: 1
  tc_bps: 10
  outdir_root: validation/runs

outputs:
  write_inputs: true
  inputs_outdir_root: validation/inputs
